# Generated by Django 5.0.1 on 2024-01-27 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_discount_remove_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=0.1, message='Discount should be minimum of 0.1%%'), django.core.validators.MaxValueValidator(limit_value=99.99, message='Discount should not exceed 99.99%%')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
