# Generated by Django 5.0.1 on 2024-01-31 15:31

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_inventory_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='store.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=50)]),
        ),
    ]
