# Generated by Django 5.0.1 on 2024-01-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
    ]
