# Generated by Django 5.0.1 on 2024-01-29 16:18

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[order.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(validators=[order.models.validate_quantity]),
        ),
    ]
